#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Render B1 Slot S4 figures: RLC damped transient.

Source: data/b1_s4_rlc.csv  (generated by probe_b1_rlc.py)
  R=2 Ohm, L=100 mH, C=100 uF underdamped series RLC step response.
  v(t) = exp(-alpha*t) * cos(omega_d*t),  alpha=10 rad/s, f_d=50.3 Hz
  Sample rate: 2 kHz, duration: 500 ms, 1000 samples.

The spectrum is a broad Lorentzian centred at f_d, with half-power
width determined by the decay constant alpha/(2*pi) = 1.6 Hz.
Contrasts with S2/S3 (periodic, narrow peaks): this is a transient
with internal periodicity -- "ringing" -- giving broad spectral content.

Outputs written to docs/shad/figures/:
  fig-b1-s4-input.png      decaying oscillation in time domain
  fig-b1-s4-spectrum.png   Lorentzian power spectrum
  fig-b1-s4-takeaway.png   annotated with f_d, Lorentzian FWHM, circuit params

Run:
    python render_b1_s4.py
"""
from __future__ import annotations

import csv
import pathlib

import matplotlib.pyplot as plt
import numpy as np

HERE   = pathlib.Path(__file__).resolve().parent
REPO   = HERE.parent.parent.parent
DATA   = HERE / "data" / "b1_s4_rlc.csv"
OUTDIR = REPO / "docs" / "shad" / "figures"

R        = 2.0
L        = 0.100
C        = 100e-6
F_SAMPLE = 2_000.0

OMEGA_0  = 1.0 / np.sqrt(L * C)
ALPHA    = R / (2.0 * L)
OMEGA_D  = np.sqrt(OMEGA_0**2 - ALPHA**2)
F_D      = OMEGA_D / (2.0 * np.pi)
TAU      = 1.0 / ALPHA
FWHM_HZ  = ALPHA / np.pi   # Lorentzian FWHM = alpha/pi


def load() -> tuple[np.ndarray, np.ndarray]:
    t_list, v_list = [], []
    with open(DATA) as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            t_list.append(float(row["time_s"]))
            v_list.append(float(row["voltage_V"]))
    return np.array(t_list), np.array(v_list)


def lorentzian(f, f0, gamma):
    return (gamma / (2.0 * np.pi)) / ((f - f0)**2 + (gamma / (2.0 * np.pi))**2)


def main() -> int:
    OUTDIR.mkdir(parents=True, exist_ok=True)

    if not DATA.exists():
        print(f"ERROR: {DATA} not found. Run probe_b1_rlc.py first.")
        return 1

    t, v = load()
    N     = len(t)
    spec  = np.fft.fft(v) / N
    freq  = np.fft.fftfreq(N, d=1.0 / F_SAMPLE)
    half  = N // 2
    mag   = np.abs(spec[:half])
    f_h   = freq[:half]

    peak_bin = int(np.argmax(mag))
    peak_hz  = f_h[peak_bin]

    # ---- input figure ----
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.plot(t * 1000, v, color="#1f4e79", linewidth=1.2)
    ax.axhline(0, color="black", linewidth=0.4)
    # envelope
    ax.plot(t * 1000,  np.exp(-ALPHA * t), "--", color="#a02020",
            linewidth=0.9, alpha=0.7, label=f"envelope  $e^{{-t/\\tau}}$,  $\\tau$={TAU*1000:.0f} ms")
    ax.plot(t * 1000, -np.exp(-ALPHA * t), "--", color="#a02020",
            linewidth=0.9, alpha=0.7)
    ax.set_xlabel("time (ms)")
    ax.set_ylabel("voltage (V, normalised)")
    ax.set_title(f"S4 RLC step response — R={R:.0f} $\\Omega$, L={L*1000:.0f} mH, C={C*1e6:.0f} $\\mu$F\n"
                 f"$f_d$ = {F_D:.1f} Hz,  $\\tau$ = {TAU*1000:.0f} ms  ({N} samples at {F_SAMPLE:.0f} Hz)")
    ax.legend(fontsize=9, loc="upper right")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s4-input.png", dpi=120)
    plt.close(fig)

    # ---- spectrum figure: magnitude ----
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.plot(f_h, mag, color="#702020", linewidth=1.2)
    ax.set_xlabel("frequency (Hz)")
    ax.set_ylabel("$|X[k]|$")
    ax.set_title(f"S4 spectrum: Lorentzian centred at $f_d$ = {F_D:.1f} Hz\n"
                 f"FWHM = $\\alpha/\\pi$ = {FWHM_HZ:.2f} Hz  (from decay constant $\\tau$ = {TAU*1000:.0f} ms)")
    ax.set_xlim(0, min(200, f_h[-1]))
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s4-spectrum.png", dpi=120)
    plt.close(fig)

    # ---- takeaway: annotated Lorentzian ----
    # Analytic Lorentzian for overlay
    f_fine   = np.linspace(1.0, 150.0, 2000)
    lor_fine = lorentzian(f_fine, F_D, 2.0 * np.pi * FWHM_HZ)
    lor_fine /= lor_fine.max()
    mag_norm  = mag / mag.max()

    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.plot(f_h, mag_norm, color="#1f4e79", linewidth=1.2, label="DFT magnitude (normalised)")
    ax.plot(f_fine, lor_fine, "--", color="#a02020", linewidth=1.2, alpha=0.8,
            label=f"Lorentzian fit  $f_d$={F_D:.1f} Hz,  FWHM={FWHM_HZ:.2f} Hz")

    # Annotate peak
    ax.axvline(peak_hz, color="#a02020", linewidth=0.7, linestyle=":", alpha=0.7)
    ax.annotate(f"peak at {peak_hz:.0f} Hz\n(expected {F_D:.1f} Hz)",
                xy=(peak_hz, 1.0), xytext=(peak_hz + 10, 0.85),
                fontsize=9, color="#a02020",
                arrowprops=dict(arrowstyle="->", color="#a02020", linewidth=0.7))

    # FWHM annotation
    half_power = 0.5
    ax.axhline(half_power, color="#2e6e3a", linewidth=0.7, linestyle="--", alpha=0.7)
    ax.annotate(f"FWHM = {FWHM_HZ:.2f} Hz\n$= \\alpha / \\pi$",
                xy=(F_D + FWHM_HZ, half_power), xytext=(F_D + FWHM_HZ + 8, 0.6),
                fontsize=9, color="#2e6e3a",
                arrowprops=dict(arrowstyle="->", color="#2e6e3a", linewidth=0.7))

    ax.set_xlabel("frequency (Hz)")
    ax.set_ylabel("$|X[k]|$ (normalised)")
    ax.set_title(f"S4 takeaway: broad Lorentzian — a transient has spectral width,\n"
                 f"unlike periodic signals (S2/S3). Width = 1/(2$\\pi\\tau$) = {FWHM_HZ:.2f} Hz")
    ax.set_xlim(0, 150)
    ax.legend(fontsize=9, loc="upper right")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s4-takeaway.png", dpi=120)
    plt.close(fig)

    print(f"S4 figures rendered.")
    print(f"  R={R:.0f} Ohm  L={L*1000:.0f} mH  C={C*1e6:.0f} uF")
    print(f"  f_d      = {F_D:.2f} Hz  (peak at {peak_hz:.2f} Hz)")
    print(f"  tau      = {TAU*1000:.0f} ms")
    print(f"  FWHM     = {FWHM_HZ:.3f} Hz  (= alpha/pi = {ALPHA/np.pi:.3f})")
    print(f"  N        = {N}")
    print(f"  out dir  = {OUTDIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
