#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Render B1 Slot S3 figures: 1 kHz triangle wave.

Source: data/b1_s3_triangle.csv  (generated by probe_b1_triangle.py)
  1000 Hz triangle wave, 50 kHz sample rate, 100 ms, 1.0 V peak.
  Analytically derived: (2/pi) * arcsin(sin(2*pi*f*t)).

Contrasts with S2 (square wave): same fundamental, different harmonic
envelope. Square wave: 1/n (flat falloff). Triangle wave: 1/n^2 (fast falloff).
The DFT makes this difference immediately visible.

Outputs written to docs/shad/figures/:
  fig-b1-s3-input.png      time-domain waveform (first 5 ms)
  fig-b1-s3-spectrum.png   one-sided magnitude spectrum
  fig-b1-s3-takeaway.png   S2 vs S3 overlay: same fundamental, different envelope

Run:
    python render_b1_s3.py
"""
from __future__ import annotations

import csv
import pathlib

import matplotlib.pyplot as plt
import numpy as np

HERE     = pathlib.Path(__file__).resolve().parent
REPO     = HERE.parent.parent.parent
DATA_S3  = HERE / "data" / "b1_s3_triangle.csv"
DATA_S2  = HERE / "data" / "b1_s2_squarewave.csv"
OUTDIR   = REPO / "docs" / "shad" / "figures"

F_SIGNAL = 1_000.0
F_SAMPLE = 50_000.0


def load_csv(path: pathlib.Path) -> tuple[np.ndarray, np.ndarray]:
    t_list, v_list = [], []
    with open(path) as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            t_list.append(float(row["time_s"]))
            v_list.append(float(row["voltage_V"]))
    return np.array(t_list), np.array(v_list)


def main() -> int:
    OUTDIR.mkdir(parents=True, exist_ok=True)

    if not DATA_S3.exists():
        print(f"ERROR: {DATA_S3} not found. Run probe_b1_triangle.py first.")
        return 1

    t, v = load_csv(DATA_S3)
    N     = len(t)
    spec  = np.fft.fft(v) / N
    freq  = np.fft.fftfreq(N, d=1.0 / F_SAMPLE)
    half  = N // 2
    mag   = np.abs(spec[:half])
    f_h   = freq[:half]

    peak_bin = int(np.argmax(mag))
    peak_hz  = f_h[peak_bin]
    peak_amp = mag[peak_bin]

    harm_bins = [round(n * F_SIGNAL / (F_SAMPLE / N)) for n in [1, 3, 5, 7, 9, 11, 13]]

    # ---- input figure ----
    n_show = int(5e-3 * F_SAMPLE)
    fig, ax = plt.subplots(figsize=(9, 3.4))
    ax.plot(t[:n_show] * 1000, v[:n_show], color="#1f4e79", linewidth=1.4)
    ax.axhline(0, color="black", linewidth=0.4)
    ax.set_xlabel("time (ms)")
    ax.set_ylabel("voltage (V)")
    ax.set_title(f"S3 triangle wave — first 5 ms (5 cycles at {F_SIGNAL:.0f} Hz, {F_SAMPLE/1e3:.0f} kHz sample rate)")
    ax.set_ylim(-1.3, 1.3)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s3-input.png", dpi=120)
    plt.close(fig)

    # ---- spectrum figure ----
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.semilogy(f_h / 1e3, mag + 1e-8, color="#702020", linewidth=0.8, alpha=0.9)
    ax.set_xlabel("frequency (kHz)")
    ax.set_ylabel("$|X[k]|$ (log scale)")
    ax.set_title(f"S3 spectrum: same odd harmonics as S2, but 1/n² envelope (much faster falloff)")
    ax.set_xlim(0, 15)
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s3-spectrum.png", dpi=120)
    plt.close(fig)

    # ---- takeaway: S2 vs S3 overlay ----
    if DATA_S2.exists():
        _, v2 = load_csv(DATA_S2)
        N2     = len(v2)
        spec2  = np.fft.fft(v2) / N2
        mag2   = np.abs(spec2[:N2 // 2])
        f_h2   = np.fft.fftfreq(N2, d=1.0 / F_SAMPLE)[:N2 // 2]
    else:
        mag2, f_h2 = None, None

    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.semilogy(f_h / 1e3, mag + 1e-8, color="#1f4e79", linewidth=1.0,
                label="S3 triangle  ($1/n^2$ envelope)")
    if mag2 is not None:
        ax.semilogy(f_h2 / 1e3, mag2 + 1e-8, color="#a02020", linewidth=1.0,
                    alpha=0.6, linestyle="--", label="S2 square  ($1/n$ envelope)")

    # envelopes
    n_vals  = np.array([1, 3, 5, 7, 9, 11, 13], dtype=float)
    env_f   = n_vals * F_SIGNAL / 1e3
    env_tri = (4.0 / np.pi**2) / n_vals**2
    env_sq  = (2.0 / np.pi)    / n_vals
    ax.semilogy(env_f, env_tri, "v", color="#1f4e79", markersize=6, alpha=0.8,
                label="$4/(\\pi^2 n^2)$")
    ax.semilogy(env_f, env_sq,  "^", color="#a02020", markersize=6, alpha=0.8,
                label="$2/(\\pi n)$")

    ax.set_xlabel("frequency (kHz)")
    ax.set_ylabel("$|X[k]|$ (log scale)")
    ax.set_title("S3 takeaway: same fundamental, same odd harmonics — but 1/$n^2$ vs 1/$n$ envelope")
    ax.set_xlim(0, 15)
    ax.legend(fontsize=9, loc="upper right")
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s3-takeaway.png", dpi=120)
    plt.close(fig)

    print(f"S3 figures rendered.")
    print(f"  N           = {N}")
    print(f"  Peak        = {peak_hz:.1f} Hz,  |X| = {peak_amp:.4f}")
    print(f"  Expected    = 4/pi^2 = {4/np.pi**2:.4f}")
    print(f"  3rd harmonic: {f_h[harm_bins[1]]:.0f} Hz,  |X| = {mag[harm_bins[1]]:.6f}  (expected {4/(9*np.pi**2):.6f})")
    print(f"  out dir     = {OUTDIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
