#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Push Chapter B0 Slot S1 (golden vector cos1_plus_cos2) through every
reference component the project ships, capture each output, plot them
all together to visualise agreement.

Components invoked:
  1. NumPy   - np.fft.fft (baseline; project does not own this kernel)
  2. C++     - lege-artis/fourier C++ reference (this project)
  3. Fortran - lege-artis/fourier Fortran reference (this project)

Build prerequisites (one-time):
  cd backends/cpp     && make
  cd backends/fortran && make
  cd backends/cpp     && g++ -O0 -g -std=c++17 -Iinclude \
                        ../../examples/shad/b1-scope/run_cpp_kernel.cpp \
                        build/dft_kernel.o \
                        -o ../../examples/shad/b1-scope/run_cpp_kernel

Outputs (in docs/shad/figures/):
  fig-s1-components.png      All available kernels' spectra on one axis
  fig-s1-components-err.png  Per-bin abs error vs the oracle, all kernels

Run:
    python render_components.py
"""
from __future__ import annotations

import csv
import io
import json
import pathlib
import shutil
import subprocess
import sys

import matplotlib.pyplot as plt
import numpy as np


HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent.parent
GOLDEN = REPO / "shared" / "golden-vectors" / "dft_n=64.json"
OUTDIR = REPO / "docs" / "shad" / "figures"

CPP_CLI     = HERE / "run_cpp_kernel"
FORTRAN_CLI = HERE / "run_fortran_kernel"
FORTRAN_DAT = REPO / "backends" / "fortran" / "build" / "golden" / "dft_n_64.dat"


def load_oracle(path, case_name):
    data = json.loads(path.read_text())
    case = data["test_cases"][case_name]
    x         = np.array([complex(re, im) for re, im in case["input"]])
    X_oracle  = np.array([complex(re, im) for re, im in case["output"]])
    return data["N"], x, X_oracle


def run_numpy(x):
    return np.fft.fft(x)


def run_cpp(case_name):
    """Invoke the C++ CLI in --csv mode and parse the output."""
    if not CPP_CLI.exists():
        return None
    cmd = [str(CPP_CLI), str(GOLDEN), case_name, "--csv"]
    out = subprocess.check_output(cmd, text=True)
    reader = csv.DictReader(io.StringIO(out))
    rows = list(reader)
    X = np.array([complex(float(r["re"]), float(r["im"])) for r in rows])
    return X


def run_fortran(case_name):
    """Invoke run_fortran_kernel in --csv mode and parse the spectrum.

    Pre-requisites (one-time on the build host):
        cd backends/fortran && make
        python tools/json_to_fortran_data.py
        gfortran -O0 -g -std=f2018 -fimplicit-none -ffp-contract=off \\
          -Ibackends/fortran/build \\
          examples/shad/b1-scope/run_fortran_kernel.f90 \\
          backends/fortran/build/dft_kernel.o \\
          -o examples/shad/b1-scope/run_fortran_kernel

    The .dat fixture must exist at FORTRAN_DAT (regenerated by the
    json_to_fortran_data tool from shared/golden-vectors/dft_n=64.json).
    Returns None gracefully if either the binary or the fixture is
    missing, so render_components.py degrades to numpy+C++ overlay only.
    """
    if not FORTRAN_CLI.exists():
        return None
    if not FORTRAN_DAT.exists():
        return None
    cmd = [str(FORTRAN_CLI), str(FORTRAN_DAT), case_name, "--csv"]
    out = subprocess.check_output(cmd, text=True)
    reader = csv.DictReader(io.StringIO(out))
    rows = list(reader)
    X = np.array([complex(float(r["re"]), float(r["im"])) for r in rows])
    return X


def main() -> int:
    OUTDIR.mkdir(parents=True, exist_ok=True)

    N, x, X_oracle = load_oracle(GOLDEN, "cos1_plus_cos2")
    half = N // 2

    X_numpy = run_numpy(x)
    X_cpp   = run_cpp("cos1_plus_cos2")
    X_fort  = run_fortran("cos1_plus_cos2")

    # ---- per-kernel max abs error vs the oracle ----
    err = {}
    err["NumPy"]   = float(np.max(np.abs(X_numpy - X_oracle)))
    if X_cpp is not None:
        err["lege-artis C++"] = float(np.max(np.abs(X_cpp - X_oracle)))
    if X_fort is not None:
        err["lege-artis Fortran"] = float(np.max(np.abs(X_fort - X_oracle)))

    print(f"--- per-kernel max abs error vs oracle (N={N}) ---")
    for name, e in err.items():
        print(f"  {name:>22s}   {e:.3e}")

    # ---- spectrum overlay ----
    bins = np.arange(half)
    fig, ax = plt.subplots(figsize=(8, 3.6))
    ax.plot(bins, np.abs(X_numpy[:half]),
            "o", markersize=6, label="NumPy", color="#1f4e79", alpha=0.85)
    if X_cpp is not None:
        ax.plot(bins, np.abs(X_cpp[:half]),
                "x", markersize=8, label="lege-artis C++", color="#a02020", alpha=0.9)
    if X_fort is not None:
        ax.plot(bins, np.abs(X_fort[:half]),
                "+", markersize=9, label="lege-artis Fortran", color="#2e6e3a", alpha=0.9)
    ax.set_xlabel("frequency bin $k$")
    ax.set_ylabel("$|X[k]|$")
    ax.set_title("S1 component agreement: numpy vs lege-artis kernels")
    ax.grid(alpha=0.3)
    ax.legend(loc="upper right")
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-s1-components.png", dpi=120)
    plt.close(fig)

    # ---- per-bin abs error plot (log scale, vs oracle) ----
    fig, ax = plt.subplots(figsize=(8, 3.6))
    ax.semilogy(bins, np.abs(X_numpy[:half] - X_oracle[:half]) + 1e-20,
                "o-", markersize=4, label="NumPy", color="#1f4e79", alpha=0.85)
    if X_cpp is not None:
        ax.semilogy(bins, np.abs(X_cpp[:half] - X_oracle[:half]) + 1e-20,
                    "x-", markersize=5, label="lege-artis C++", color="#a02020", alpha=0.9)
    if X_fort is not None:
        ax.semilogy(bins, np.abs(X_fort[:half] - X_oracle[:half]) + 1e-20,
                    "+-", markersize=5, label="lege-artis Fortran", color="#2e6e3a", alpha=0.9)
    ax.axhline(1e-13, color="black", linestyle=":", linewidth=0.7, alpha=0.6, label="strict gate 1e-13")
    ax.axhline(1e-12, color="black", linestyle="--", linewidth=0.7, alpha=0.6, label="eng. gate 1e-12 (N=64)")
    ax.set_xlabel("frequency bin $k$")
    ax.set_ylabel("|X[k] - X_oracle[k]|")
    ax.set_title("S1 per-bin oracle disagreement, log scale")
    ax.grid(alpha=0.3, which="both")
    ax.legend(loc="upper right", fontsize=8)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-s1-components-err.png", dpi=120)
    plt.close(fig)

    print(f"\n  figures -> {OUTDIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
