#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Render B1 Slot S2 figures: 1 kHz square wave.

Source: data/b1_s2_squarewave.csv  (generated by probe_b1_squarewave.py)
  1000 Hz square wave, 50 kHz sample rate, 100 ms, 1.0 V peak.
  Analytically derived: exact mathematical definition of a square wave.

Outputs written to docs/shad/figures/:
  fig-b1-s2-input.png      time-domain waveform (first 5 ms, 5 cycles)
  fig-b1-s2-spectrum.png   one-sided magnitude spectrum (log scale)
  fig-b1-s2-takeaway.png   annotated spectrum: 1/n harmonic envelope labelled

Run:
    python render_b1_s2.py
"""
from __future__ import annotations

import csv
import pathlib

import matplotlib.pyplot as plt
import numpy as np

HERE   = pathlib.Path(__file__).resolve().parent
REPO   = HERE.parent.parent.parent
DATA   = HERE / "data" / "b1_s2_squarewave.csv"
OUTDIR = REPO / "docs" / "shad" / "figures"

F_SIGNAL = 1_000.0
F_SAMPLE = 50_000.0


def load() -> tuple[np.ndarray, np.ndarray]:
    t_list, v_list = [], []
    with open(DATA) as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            t_list.append(float(row["time_s"]))
            v_list.append(float(row["voltage_V"]))
    return np.array(t_list), np.array(v_list)


def main() -> int:
    OUTDIR.mkdir(parents=True, exist_ok=True)

    if not DATA.exists():
        print(f"ERROR: {DATA} not found. Run probe_b1_squarewave.py first.")
        return 1

    t, v = load()
    N     = len(t)
    spec  = np.fft.fft(v) / N
    freq  = np.fft.fftfreq(N, d=1.0 / F_SAMPLE)
    half  = N // 2
    mag   = np.abs(spec[:half])
    f_h   = freq[:half]

    peak_bin = int(np.argmax(mag))
    peak_hz  = f_h[peak_bin]
    peak_amp = mag[peak_bin]

    # harmonic bins: k=1,3,5,...  n_harm = 1,3,5,...
    harm_bins = [round(n * F_SIGNAL / (F_SAMPLE / N)) for n in [1, 3, 5, 7, 9, 11, 13]]

    # ---- input figure: first 5 ms (5 cycles) ----
    n_show = int(5e-3 * F_SAMPLE)
    fig, ax = plt.subplots(figsize=(9, 3.4))
    ax.step(t[:n_show] * 1000, v[:n_show], where="post",
            color="#1f4e79", linewidth=1.2)
    ax.axhline(0, color="black", linewidth=0.4)
    ax.set_xlabel("time (ms)")
    ax.set_ylabel("voltage (V)")
    ax.set_title(f"S2 square wave — first 5 ms (5 cycles at {F_SIGNAL:.0f} Hz, {F_SAMPLE/1e3:.0f} kHz sample rate)")
    ax.set_ylim(-1.3, 1.3)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s2-input.png", dpi=120)
    plt.close(fig)

    # ---- spectrum figure: log scale, full range ----
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.semilogy(f_h / 1e3, mag + 1e-6, color="#702020", linewidth=0.8, alpha=0.9)
    ax.set_xlabel("frequency (kHz)")
    ax.set_ylabel("$|X[k]|$ (log scale)")
    ax.set_title(f"S2 spectrum: odd harmonics at 1, 3, 5, 7, ... kHz  |  1/n amplitude envelope")
    ax.set_xlim(0, 25)
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s2-spectrum.png", dpi=120)
    plt.close(fig)

    # ---- takeaway: annotated harmonic series ----
    fig, ax = plt.subplots(figsize=(9, 3.8))
    ax.semilogy(f_h / 1e3, mag + 1e-6, color="#1f4e79", linewidth=0.6, alpha=0.5)

    for n_idx, k in enumerate(harm_bins[:7]):
        if k < half:
            n_harm = 2 * n_idx + 1
            f_hz   = f_h[k]
            m      = mag[k]
            expected = (2.0 / (np.pi * n_harm))
            ax.semilogy(f_hz / 1e3, m, "o", color="#a02020", markersize=7, alpha=0.9)
            ax.annotate(f"$n$={n_harm}\n{f_hz/1e3:.0f} kHz\n|X|={m:.3f}",
                        xy=(f_hz / 1e3, m),
                        xytext=(f_hz / 1e3 + 0.3, m * 1.6),
                        fontsize=7, color="#a02020",
                        arrowprops=dict(arrowstyle="-", color="#a02020",
                                        linewidth=0.6))

    # 1/n envelope overlay
    n_vals = np.array([1, 3, 5, 7, 9, 11, 13], dtype=float)
    env_f  = n_vals * F_SIGNAL / 1e3
    env_m  = (2.0 / np.pi) / n_vals
    ax.semilogy(env_f, env_m, "--", color="#2e6e3a", linewidth=1.0,
                alpha=0.8, label="$2/(\\pi n)$ envelope")

    ax.set_xlabel("frequency (kHz)")
    ax.set_ylabel("$|X[k]|$ (log scale)")
    ax.set_title(f"S2 takeaway: square-wave odd harmonics match 2/(πn) envelope exactly")
    ax.set_xlim(0, 15)
    ax.legend(fontsize=9, loc="upper right")
    ax.grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig(OUTDIR / "fig-b1-s2-takeaway.png", dpi=120)
    plt.close(fig)

    print(f"S2 figures rendered.")
    print(f"  N           = {N}")
    print(f"  Peak        = {peak_hz:.1f} Hz,  |X| = {peak_amp:.4f}")
    print(f"  Expected    = 2/pi = {2/np.pi:.4f}")
    print(f"  3rd harmonic: {f_h[harm_bins[1]]:.0f} Hz,  |X| = {mag[harm_bins[1]]:.4f}  (expected {2/(3*np.pi):.4f})")
    print(f"  out dir     = {OUTDIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
