<?php
/**
 * runner.php — MI-M-T migration runner (PHP 8.x PDO)
 * tags:    [μS-CAND][TRIG-REQ][CRIT-AUDIT]
 * date:    2026-04-27
 * author:  pete
 * version: 0.1.0 (D-01)
 *
 * Citation: ARCH-SPEC §8.3 (token table), §8.4 (schema_migrations),
 *           §8.5 (runner contracts), §0.3 (canonical types), §0.4 (constraints)
 *           DEV-SONNET-INSTRUCTIONS §3 (ground rules), §7 (portability matrix)
 *
 * Usage (CLI):
 *   php runner.php [--engine=mysql|postgres|sqlite] [--db-url=DSN] [--help]
 *   php runner.php                         # defaults to MySQL (Active24 target)
 *   php runner.php --engine=sqlite --db-url=sqlite:/tmp/test.sqlite
 *
 * Usage (HTTP — place runner.php in a non-public directory; protect with secret):
 *   GET /admin/runner.php?secret=<RUNNER_SECRET>&engine=mysql
 *   The HTTP variant reads DB credentials from environment variables or a
 *   credentials file (never from query parameters).
 *
 * Environment variables (override defaults):
 *   MIMT_DB_HOST, MIMT_DB_PORT, MIMT_DB_NAME, MIMT_DB_USER, MIMT_DB_PASS
 *   MIMT_RUNNER_SECRET  (HTTP mode — required; request blocked if absent)
 *
 * Behaviour:
 *   1. Collect NNN_*.sql files from the same directory, sorted.
 *   2. Substitute canonical tokens for the target engine.
 *   3. For each file:
 *      a. Extract the UP section.
 *      b. Compute SHA-256 of the raw UP section (pre-substitution).
 *      c. Check schema_migrations:
 *         - absent  → apply + record.
 *         - present, hash matches → skip.
 *         - present, hash differs → ABORT (drift detection — ARCH-SPEC §8.4).
 *
 * Portability notes:
 *   - MySQL (primary target for Active24): PDO + mysql DSN.
 *   - PostgreSQL: PDO + pgsql DSN.
 *   - SQLite: PDO + sqlite DSN (dev/LDE only).
 */

declare(strict_types=1);

// ─── Token replacement table — ARCH-SPEC §8.3 ────────────────────────────

const TOKENS = [
    'mysql' => [
        '{{PK_BIGINT_AUTOINC}}' => 'BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY',
        '{{TABLE_OPTIONS}}'     => ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
        '{{JSON_TYPE}}'         => 'JSON',
        '{{BOOL_TYPE}}'         => 'TINYINT(1)',
        '{{TS_TYPE}}'           => 'DATETIME',
        '{{TABLE_CONSTRAINTS}}' => '',
    ],
    'postgres' => [
        '{{PK_BIGINT_AUTOINC}}' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        '{{TABLE_OPTIONS}}'     => '',
        '{{JSON_TYPE}}'         => 'JSONB',
        '{{BOOL_TYPE}}'         => 'BOOLEAN',
        '{{TS_TYPE}}'           => 'TIMESTAMP',
        '{{TABLE_CONSTRAINTS}}' => '',
    ],
    'sqlite' => [
        '{{PK_BIGINT_AUTOINC}}' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
        '{{TABLE_OPTIONS}}'     => '',
        '{{JSON_TYPE}}'         => 'TEXT',
        '{{BOOL_TYPE}}'         => 'INTEGER',
        '{{TS_TYPE}}'           => 'TEXT',
        '{{TABLE_CONSTRAINTS}}' => '',
    ],
];

// ─── Default DSNs (LDE) ───────────────────────────────────────────────────

function default_dsn(string $engine): array {
    $host = getenv('MIMT_DB_HOST') ?: '127.0.0.1';
    $port = getenv('MIMT_DB_PORT') ?: ($engine === 'postgres' ? '5432' : '3306');
    $name = getenv('MIMT_DB_NAME') ?: 'mimt_dev';
    $user = getenv('MIMT_DB_USER') ?: ($engine === 'mysql' ? 'root' : 'postgres');
    $pass = getenv('MIMT_DB_PASS') ?: '';

    return match ($engine) {
        'mysql'    => [
            'dsn'  => "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",
            'user' => $user,
            'pass' => $pass,
        ],
        'postgres' => [
            'dsn'  => "pgsql:host={$host};port={$port};dbname={$name}",
            'user' => $user,
            'pass' => $pass,
        ],
        'sqlite'   => [
            'dsn'  => 'sqlite:/tmp/mimt_dev.sqlite',
            'user' => '',
            'pass' => '',
        ],
        default    => throw new \InvalidArgumentException("Unknown engine: {$engine}"),
    };
}

// ─── Helpers ─────────────────────────────────────────────────────────────

function apply_tokens(string $sql, string $engine): string {
    $map = TOKENS[$engine];
    return str_replace(array_keys($map), array_values($map), $sql);
}

function extract_up_section(string $sql): string {
    $pos = stripos($sql, '-- DOWN BEGIN');
    return $pos !== false ? substr($sql, 0, $pos) : $sql;
}

function sha256_of(string $content): string {
    return hash('sha256', trim($content));
}

function parse_version(string $filename): string {
    return explode('_', basename($filename))[0];
}

function parse_description(string $filename): string {
    $stem = pathinfo(basename($filename), PATHINFO_FILENAME); // "000_create_schema_migrations"
    return str_replace('_', ' ', substr($stem, 4));           // "create schema migrations"
}

function collect_migration_files(): array {
    $dir   = __DIR__;
    $files = glob("{$dir}/[0-9][0-9][0-9]_*.sql");
    sort($files);
    return $files;
}

// ─── Schema / tracking helpers ───────────────────────────────────────────

function schema_migrations_exists(\PDO $pdo, string $engine): bool {
    try {
        return match ($engine) {
            'mysql'  => (bool) $pdo->query("SHOW TABLES LIKE 'schema_migrations'")->fetchColumn(),
            'postgres' => (bool) $pdo->query(
                "SELECT to_regclass('public.schema_migrations')"
            )->fetchColumn(),
            'sqlite' => (bool) $pdo->query(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='schema_migrations'"
            )->fetchColumn(),
            default  => false,
        };
    } catch (\PDOException $e) {
        return false;
    }
}

function get_recorded_hash(\PDO $pdo, string $version): ?string {
    $stmt = $pdo->prepare(
        'SELECT sha256_hex FROM schema_migrations WHERE version = ?'
    );
    $stmt->execute([$version]);
    $row = $stmt->fetch(\PDO::FETCH_NUM);
    return $row ? $row[0] : null;
}

function record_migration(
    \PDO $pdo,
    string $version,
    string $description,
    string $sha256,
    int $duration_ms,
    string $engine
): void {
    $now = gmdate('Y-m-d\TH:i:s\Z');  // UTC ISO-8601
    $by  = "runner.php/{$engine}";
    $stmt = $pdo->prepare(
        'INSERT INTO schema_migrations
         (version, description, applied_at, applied_by, sha256_hex, duration_ms)
         VALUES (?, ?, ?, ?, ?, ?)'
    );
    $stmt->execute([$version, $description, $now, $by, $sha256, $duration_ms]);
}

// ─── Core apply logic ────────────────────────────────────────────────────

/**
 * Apply one migration file.
 * Returns: 'applied' | 'skipped'
 * Throws RuntimeException on drift detection.
 */
function apply_migration_file(
    string $path,
    \PDO $pdo,
    string $engine
): string {
    $raw_sql     = file_get_contents($path);
    $version     = parse_version($path);
    $description = parse_description($path);

    $up_raw          = extract_up_section($raw_sql);
    $up_substituted  = apply_tokens($up_raw, $engine);
    $sha256          = sha256_of($up_raw);  // Hash on canonical (pre-substitution) form

    $recorded_hash = get_recorded_hash($pdo, $version);

    if ($recorded_hash !== null) {
        if ($recorded_hash === $sha256) {
            log_line("  [{$version}] SKIP  — already applied, hash matches.");
            return 'skipped';
        }
        throw new \RuntimeException(
            "DRIFT DETECTED for version {$version}: "
            . "recorded sha256=" . substr($recorded_hash, 0, 12) . "… "
            . "file sha256=" . substr($sha256, 0, 12) . "… "
            . "— refusing apply (ARCH-SPEC §8.4)."
        );
    }

    // Apply: split on semicolons, execute each non-empty statement
    $t0         = hrtime(true);
    $statements = array_filter(
        array_map('trim', explode(';', $up_substituted)),
        fn(string $s): bool => $s !== ''
    );
    foreach ($statements as $stmt) {
        $pdo->exec($stmt);
    }
    $duration_ms = (int) ((hrtime(true) - $t0) / 1_000_000);

    record_migration($pdo, $version, $description, $sha256, $duration_ms, $engine);
    log_line("  [{$version}] APPLIED — {$description} ({$duration_ms}ms, sha256=" . substr($sha256, 0, 12) . "…)");
    return 'applied';
}

// ─── Run all migrations ──────────────────────────────────────────────────

function run_migrations(string $engine, string $dsn, string $user, string $pass): void {
    log_line("\nMI-M-T migration runner v0.1.0 (PHP)");
    log_line("Engine : {$engine}");
    log_line("DSN    : {$dsn}\n");

    $files = collect_migration_files();
    if (empty($files)) {
        log_line('No migration files found in ' . __DIR__);
        return;
    }

    $pdo_options = [
        \PDO::ATTR_ERRMODE            => \PDO::ERRMODE_EXCEPTION,
        \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
        \PDO::ATTR_EMULATE_PREPARES   => false,
    ];

    $pdo = new \PDO($dsn, $user ?: null, $pass ?: null, $pdo_options);

    // SQLite: enable foreign keys per connection (ARCH-SPEC §0.4 / DEV-SONNET §3)
    if ($engine === 'sqlite') {
        $pdo->exec('PRAGMA foreign_keys = ON');
    }

    $counts = ['applied' => 0, 'skipped' => 0];

    $pdo->beginTransaction();
    try {
        foreach ($files as $path) {
            $result = apply_migration_file($path, $pdo, $engine);
            $counts[$result]++;
        }
        $pdo->commit();
    } catch (\Throwable $e) {
        $pdo->rollBack();
        log_line('ABORT: ' . $e->getMessage());
        exit(1);
    }

    log_line(
        "\nDone. applied={$counts['applied']} skipped={$counts['skipped']}"
    );

    // Print final state
    $stmt = $pdo->query(
        'SELECT version, description, applied_at, applied_by, sha256_hex, duration_ms
           FROM schema_migrations ORDER BY version'
    );
    log_line("\nschema_migrations contents:");
    log_line(sprintf('  %-8s %-22s %-18s %s', 'version', 'applied_at', 'sha256_hex[:16]', 'description'));
    log_line(sprintf('  %s %s %s %s', str_repeat('-', 8), str_repeat('-', 22), str_repeat('-', 18), str_repeat('-', 40)));
    foreach ($stmt->fetchAll() as $row) {
        log_line(sprintf(
            '  %-8s %-22s %-18s %s',
            $row['version'],
            $row['applied_at'],
            substr($row['sha256_hex'], 0, 16) . '…',
            $row['description']
        ));
    }
}

// ─── Logging (works in both CLI and HTTP context) ─────────────────────────

function log_line(string $msg): void {
    if (php_sapi_name() === 'cli') {
        echo $msg . PHP_EOL;
    } else {
        echo nl2br(htmlspecialchars($msg, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8')) . '<br>';
    }
}

// ─── HTTP mode — security gate ───────────────────────────────────────────

function http_security_check(): void {
    $expected = getenv('MIMT_RUNNER_SECRET');
    if (empty($expected)) {
        http_response_code(403);
        die('MIMT_RUNNER_SECRET environment variable not set — HTTP mode disabled.');
    }
    $provided = $_GET['secret'] ?? '';
    if (!hash_equals($expected, $provided)) {
        http_response_code(403);
        die('Forbidden.');
    }
}

// ─── Entry point ─────────────────────────────────────────────────────────

$is_cli = php_sapi_name() === 'cli';

if (!$is_cli) {
    http_security_check();
    header('Content-Type: text/html; charset=utf-8');
    echo '<pre>';
}

// Parse arguments
if ($is_cli) {
    $opts = getopt('', ['engine:', 'db-url:', 'help']);
    if (isset($opts['help'])) {
        echo "Usage: php runner.php [--engine=mysql|postgres|sqlite] [--db-url=DSN]\n";
        exit(0);
    }
    $engine = $opts['engine'] ?? 'mysql';  // MySQL = Active24 primary target
    $db_url = $opts['db-url'] ?? null;
} else {
    $engine = $_GET['engine'] ?? 'mysql';
    $db_url = null;
}

if (!in_array($engine, ['mysql', 'postgres', 'sqlite'], true)) {
    log_line("Invalid engine: {$engine}. Use mysql, postgres, or sqlite.");
    exit(1);
}

$conn = $db_url
    ? ['dsn' => $db_url, 'user' => '', 'pass' => '']
    : default_dsn($engine);

run_migrations($engine, $conn['dsn'], $conn['user'], $conn['pass']);

if (!$is_cli) {
    echo '</pre>';
}
