#!/usr/bin/env python3
# =============================================================================
# runner.py — MI-M-T migration runner (Python CLI)
# tags:    [μS-CAND][TRIG-REQ][CRIT-AUDIT]
# date:    2026-04-27
# author:  pete
# version: 0.1.0 (D-01)
# =============================================================================
# Citation: ARCH-SPEC §8.3 (token table), §8.4 (schema_migrations),
#           §8.5 (runner contracts), §0.3 (canonical types), §0.4 (constraints)
#           DEV-SONNET-INSTRUCTIONS §3 (ground rules), §7 (portability matrix)
#
# Usage:
#   python runner.py --engine sqlite   [--db-url sqlite:////path/to/db.sqlite]
#   python runner.py --engine mysql    [--db-url mysql+pymysql://user:pw@host/db]
#   python runner.py --engine postgres [--db-url postgresql+psycopg2://user:pw@host/db]
#
# Default db-urls (LDE):
#   sqlite:   file:///3-fold-path/.test/d01.sqlite
#   mysql:    mysql+pymysql://root:@127.0.0.1:3306/mimt_dev
#   postgres: postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/mimt_dev
#
# Behaviour:
#   1. Collect all NNN_*.sql files from the migrations/ directory, sorted.
#   2. Substitute canonical tokens for the target engine.
#   3. For each file:
#      a. Extract the UP section (between file start and "-- DOWN BEGIN").
#      b. Compute SHA-256 of the normalised UP section.
#      c. Check schema_migrations:
#         - version absent → apply + record.
#         - version present, sha256 matches → skip (idempotent).
#         - version present, sha256 differs → ABORT (drift detected — ARCH-SPEC §8.4).
#   4. Print a summary.
#
# Portability notes:
#   - SQLite: uses BEGIN IMMEDIATE (no SELECT FOR UPDATE — ARCH-SPEC §0.4).
#   - MySQL / PostgreSQL: uses standard BEGIN / COMMIT.
#   - applied_at stored as UTC ISO-8601 string (TEXT in SQLite via {{TS_TYPE}}).
# =============================================================================

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# SQLAlchemy 2.x
from sqlalchemy import create_engine, text, inspect

# ---------------------------------------------------------------------------
# Token replacement table — ARCH-SPEC §8.3
# ---------------------------------------------------------------------------

TOKENS: dict[str, dict[str, str]] = {
    "sqlite": {
        "{{PK_BIGINT_AUTOINC}}": "INTEGER PRIMARY KEY AUTOINCREMENT",
        "{{TABLE_OPTIONS}}": "",
        "{{JSON_TYPE}}": "TEXT",
        "{{BOOL_TYPE}}": "INTEGER",
        "{{BOOL_TRUE}}": "1",       # OQ-030 (D-09): integer literal for sqlite/mysql
        "{{TS_TYPE}}": "TEXT",
        "{{TABLE_CONSTRAINTS}}": "",
    },
    "mysql": {
        "{{PK_BIGINT_AUTOINC}}": "BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY",
        "{{TABLE_OPTIONS}}": " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
        "{{JSON_TYPE}}": "JSON",
        "{{BOOL_TYPE}}": "TINYINT(1)",
        "{{BOOL_TRUE}}": "1",       # OQ-030 (D-09): TINYINT(1) default is integer
        "{{TS_TYPE}}": "DATETIME",
        "{{TABLE_CONSTRAINTS}}": "",
    },
    "postgres": {
        "{{PK_BIGINT_AUTOINC}}": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "{{TABLE_OPTIONS}}": "",
        "{{JSON_TYPE}}": "JSONB",
        "{{BOOL_TYPE}}": "BOOLEAN",
        "{{BOOL_TRUE}}": "TRUE",    # OQ-030 (D-09): PostgreSQL rejects integer literal for BOOLEAN
        "{{TS_TYPE}}": "TIMESTAMP",
        "{{TABLE_CONSTRAINTS}}": "",
    },
}

DEFAULT_URLS: dict[str, str] = {
    "sqlite":   "sqlite:////sessions/dazzling-gracious-lovelace/mnt/VibeCodeProjects/3-fold-path/.test/d01.sqlite",
    "mysql":    "mysql+pymysql://root:@127.0.0.1:3306/mimt_dev",
    "postgres": "postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/mimt_dev",
}

MIGRATIONS_DIR = Path(__file__).parent


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def apply_tokens(sql: str, engine: str) -> str:
    """Substitute canonical tokens for the target engine (ARCH-SPEC §8.3)."""
    substitutions = TOKENS[engine]
    for token, replacement in substitutions.items():
        sql = sql.replace(token, replacement)
    return sql


def split_statements(sql: str) -> list[str]:
    """
    Split SQL into executable statements using a character-level state machine.

    Handles three cases that defeat naive split(';'):
      1. Semicolons inside -- single-line comments  (e.g. comment text with ';')
      2. Semicolons inside \'...' string literals    (e.g. sync_error values)
      3. Escaped single-quotes inside strings       (e.g. O\'Brien)

    Algorithm:
      - Track in_string / in_comment state character by character.
      - Only treat ';' as a statement delimiter when in the neutral state.
      - Collect accumulated characters into statement chunks.
    """
    statements: list[str] = []
    current: list[str] = []
    in_string = False
    in_comment = False
    i = 0
    n = len(sql)

    while i < n:
        c = sql[i]

        if in_comment:
            if c == "\n":
                in_comment = False          # comment ends at newline
            i += 1
            continue

        if in_string:
            current.append(c)
            if c == "\'":
                # SQL escape: two consecutive single-quotes inside a string
                if i + 1 < n and sql[i + 1] == "\'":
                    current.append("\'")
                    i += 2
                    continue
                else:
                    in_string = False       # closing quote
            i += 1
            continue

        # Neutral state
        if c == "-" and i + 1 < n and sql[i + 1] == "-":
            in_comment = True
            i += 2
            continue

        if c == "\'":
            in_string = True
            current.append(c)
            i += 1
            continue

        if c == ";":
            stmt = "".join(current).strip()
            if stmt:
                statements.append(stmt)
            current = []
            i += 1
            continue

        current.append(c)
        i += 1

    # Trailing content after last semicolon
    stmt = "".join(current).strip()
    if stmt:
        statements.append(stmt)

    return statements


def extract_up_section(sql: str) -> str:
    """
    Return everything above the DOWN BEGIN fence.
    If no DOWN section exists, return the whole file.
    """
    match = re.search(r"--\s*DOWN BEGIN", sql, re.IGNORECASE)
    if match:
        return sql[: match.start()]
    return sql


def sha256_of(text_content: str) -> str:
    """SHA-256 of normalised (stripped) UP section — ARCH-SPEC §8.4."""
    normalised = text_content.strip()
    return hashlib.sha256(normalised.encode("utf-8")).hexdigest()


def collect_migration_files() -> list[Path]:
    """Return NNN_*.sql files in MIGRATIONS_DIR, sorted by NNN prefix."""
    files = sorted(
        MIGRATIONS_DIR.glob("[0-9][0-9][0-9]_*.sql"),
        key=lambda p: p.name,
    )
    return files


def parse_version(filename: str) -> str:
    """Extract the NNN prefix from a filename like '000_create_schema_migrations.sql'."""
    return filename.split("_")[0]


def parse_description(filename: str) -> str:
    """Extract human description from filename (strip NNN_ prefix and .sql suffix)."""
    stem = Path(filename).stem          # e.g. "000_create_schema_migrations"
    return stem[4:].replace("_", " ")  # e.g. "create schema migrations"


# ---------------------------------------------------------------------------
# Core apply logic
# ---------------------------------------------------------------------------

def schema_migrations_exists(conn, engine_type: str) -> bool:
    """Check whether schema_migrations table exists (engine-portable)."""
    if engine_type == "sqlite":
        result = conn.execute(
            text("SELECT name FROM sqlite_master WHERE type='table' AND name='schema_migrations'")
        ).fetchone()
        return result is not None
    elif engine_type == "mysql":
        result = conn.execute(
            text("SHOW TABLES LIKE 'schema_migrations'")
        ).fetchone()
        return result is not None
    else:  # postgres
        result = conn.execute(
            text(
                "SELECT to_regclass('public.schema_migrations')"
            )
        ).fetchone()
        return result is not None and result[0] is not None


def get_recorded_hash(conn, version: str) -> Optional[str]:
    """Return the sha256_hex recorded for this version, or None if absent."""
    row = conn.execute(
        text("SELECT sha256_hex FROM schema_migrations WHERE version = :v"),
        {"v": version},
    ).fetchone()
    return row[0] if row else None


def record_migration(conn, version: str, description: str, sha256: str,
                     duration_ms: int, engine_type: str) -> None:
    """Insert a row into schema_migrations (ARCH-SPEC §8.4).

    OQ-029 (D-09): applied_at must be a datetime object, not an ISO-8601 string.
    MySQL DATETIME rejects the 'Z' suffix; SQLAlchemy renders datetime objects
    correctly for all three engines (sqlite / mysql / postgres).
    """
    now_utc = datetime.now(timezone.utc).replace(tzinfo=None)  # naive UTC — portable across all engines
    conn.execute(
        text(
            "INSERT INTO schema_migrations "
            "(version, description, applied_at, applied_by, sha256_hex, duration_ms) "
            "VALUES (:version, :description, :applied_at, :applied_by, :sha256_hex, :duration_ms)"
        ),
        {
            "version": version,
            "description": description,
            "applied_at": now_utc,
            "applied_by": f"runner.py/{engine_type}",
            "sha256_hex": sha256,
            "duration_ms": duration_ms,
        },
    )


def apply_migration_file(path: Path, conn, engine_type: str, raw_sql: str) -> str:
    """
    Apply a single migration file. Returns one of: 'applied', 'skipped', 'aborted'.
    Raises RuntimeError on drift detection.
    """
    version = parse_version(path.name)
    description = parse_description(path.name)

    up_raw = extract_up_section(raw_sql)
    up_substituted = apply_tokens(up_raw, engine_type)
    sha256 = sha256_of(up_raw)  # Hash computed on pre-substitution text (canonical form)

    # Only query schema_migrations if the table already exists (bootstrap guard).
    # On first run, file 000 creates the table; we must not query it before it exists.
    if schema_migrations_exists(conn, engine_type):
        recorded_hash = get_recorded_hash(conn, version)
        if recorded_hash is not None:
            if recorded_hash == sha256:
                print(f"  [{version}] SKIP  — already applied, hash matches.")
                return "skipped"
            else:
                msg = (
                    f"DRIFT DETECTED for version {version}: "
                    f"recorded sha256={recorded_hash[:12]}… "
                    f"file sha256={sha256[:12]}… "
                    f"— refusing apply (ARCH-SPEC §8.4)."
                )
                raise RuntimeError(msg)

    # Apply — strip comments before splitting to avoid semicolons inside -- lines
    t0 = time.monotonic()
    statements = split_statements(up_substituted)
    for stmt in statements:
        conn.execute(text(stmt))
    duration_ms = int((time.monotonic() - t0) * 1000)

    record_migration(conn, version, description, sha256, duration_ms, engine_type)
    print(f"  [{version}] APPLIED — {description} ({duration_ms}ms, sha256={sha256[:12]}…)")
    return "applied"


def reset_pg_identity_sequences(conn) -> None:
    """OQ-031 (D-09): Reset PostgreSQL IDENTITY sequences after seed inserts.

    GENERATED BY DEFAULT AS IDENTITY sequences are NOT advanced when rows are
    inserted with explicit PK values (as seed migrations do). Without this fix
    the next API INSERT without an explicit id collides with seed row id=1.

    Queries information_schema to discover all 'id' identity columns in the
    public schema, then calls setval(pg_get_serial_sequence(...)) for each.
    Safe to call on an empty schema (COALESCE guards against NULL from MAX).
    """
    id_tables = conn.execute(text(
        "SELECT table_name FROM information_schema.columns "
        "WHERE column_name = 'id' AND table_schema = 'public' "
        "  AND identity_generation IS NOT NULL "
        "ORDER BY table_name"
    )).fetchall()

    reset_count = 0
    for (table_name,) in id_tables:
        conn.execute(text(
            f"SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), "
            f"  COALESCE((SELECT MAX(id) FROM {table_name}), 1))"
        ))
        reset_count += 1

    if reset_count:
        print(f"  [OQ-031] Reset {reset_count} PostgreSQL identity sequence(s).")


def run_migrations(engine_type: str, db_url: str) -> None:
    """Entry point: apply all pending migrations in order."""
    print(f"\nMI-M-T migration runner v0.1.0")
    print(f"Engine : {engine_type}")
    print(f"DB URL : {db_url}\n")

    files = collect_migration_files()
    if not files:
        print("No migration files found in", MIGRATIONS_DIR)
        return

    # SQLite: ensure parent directory exists
    if engine_type == "sqlite":
        db_path = db_url.replace("sqlite:////", "/").replace("sqlite:///", "")
        os.makedirs(os.path.dirname(db_path), exist_ok=True)

    engine = create_engine(db_url, echo=False)

    with engine.begin() as conn:
        counts = {"applied": 0, "skipped": 0, "aborted": 0}

        for path in files:
            raw_sql = path.read_text(encoding="utf-8")
            try:
                result = apply_migration_file(path, conn, engine_type, raw_sql)
                counts[result] += 1
            except RuntimeError as exc:
                print(f"  ABORT: {exc}")
                counts["aborted"] += 1
                sys.exit(1)

    # OQ-031 (D-09): PostgreSQL IDENTITY sequences don't advance on explicit-ID
    # seed inserts (GENERATED BY DEFAULT AS IDENTITY). MySQL AUTO_INCREMENT
    # self-heals; SQLite has no sequences. Reset all identity sequences after
    # migrations complete so that subsequent API inserts don't collide.
    if engine_type == "postgres":
        with engine.begin() as conn:
            reset_pg_identity_sequences(conn)

    print(f"\nDone. applied={counts['applied']} skipped={counts['skipped']} aborted={counts['aborted']}")

    # Print final state for SESSION-NOTES
    engine2 = create_engine(db_url, echo=False)
    with engine2.connect() as conn:
        rows = conn.execute(
            text("SELECT version, description, applied_at, applied_by, sha256_hex, duration_ms "
                 "FROM schema_migrations ORDER BY version")
        ).fetchall()
        print("\nschema_migrations contents:")
        print(f"  {'version':<8} {'applied_at':<22} {'sha256_hex[:16]':<18} {'description'}")
        print(f"  {'-'*8} {'-'*22} {'-'*18} {'-'*40}")
        for row in rows:
            print(f"  {row[0]:<8} {str(row[2]):<22} {row[4][:16]+'…':<18} {row[1]}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="MI-M-T migration runner — applies NNN_*.sql files in order."
    )
    parser.add_argument(
        "--engine",
        choices=["sqlite", "mysql", "postgres"],
        default="sqlite",
        help="Target engine (default: sqlite)",
    )
    parser.add_argument(
        "--db-url",
        default=None,
        help="SQLAlchemy connection URL (overrides default for the chosen engine)",
    )
    args = parser.parse_args()

    db_url = args.db_url or DEFAULT_URLS[args.engine]
    run_migrations(args.engine, db_url)


if __name__ == "__main__":
    main()



# ---------------------------------------------------------------------------
# Alembic integration -- env.py calls apply_pending() instead of main()
# ---------------------------------------------------------------------------

def apply_pending(engine_type: str = "sqlite", db_url: Optional[str] = None) -> None:
    """Callable entry point for Alembic env.py.

    Usage in env.py::

        from migrations.runner import apply_pending
        apply_pending(engine_type=config.get_main_option("engine"),
                      db_url=config.get_main_option("sqlalchemy.url"))
    """
    url = db_url or DEFAULT_URLS[engine_type]
    run_migrations(engine_type, url)
