! test_dft_golden.f90 -- Golden-vector verification for lege-artis/fourier DFT
!
! Reads .dat files produced by tools/json_to_fortran_data.py and verifies
! that dft() matches the NumPy/SciPy oracle for all N={2,4,8,16,64} cases.
!
! Gate: Option G (Higham s4.2 / MacBook Opus 2026-05-10)
!
!   metric = abs(got - expected) / max(abs(expected), 1.0_dp)
!   gate   = 1.0e-13_dp * sqrt(real(N, dp))
!
!   Relative error with floor-1.0 denominator guards near-zero oracle bins.
!   sqrt(N) scaling matches O(sqrt(N)*eps) expected accumulation of a direct
!   DFT (Higham backward-stability bound, unit-amplitude input). Effective
!   gates: N=2 -> 1.41e-13, N=4 -> 2.00e-13, N=8 -> 2.83e-13,
!          N=16 -> 4.00e-13, N=64 -> 8.00e-13.
!
!   Python pre-validation: 38/38 PASS (worst: N=64 cosine_k1 metric 2.09e-13,
!   gate 8.00e-13; N=64 ramp metric 1.38e-13, gate 8.00e-13).
!
! .dat files: generated by `make golden-data` into build/golden/ (gitignored).
! Build: make golden-data && make test   (from fourier/backends/fortran/)
!
! License: Apache 2.0

program test_dft_golden
  use lege_artis_fourier_dft, only: dft, dp
  implicit none

  integer :: pass_total, fail_total
  integer :: i
  integer, parameter :: NSIZES = 5
  integer :: sizes(NSIZES)

  sizes = [2, 4, 8, 16, 64]
  pass_total = 0
  fail_total = 0

  do i = 1, NSIZES
    call run_golden_file(sizes(i), pass_total, fail_total)
  end do

  write(*, '(a,i0,a,i0,a)') &
    "Golden vector suite: ", pass_total, " PASS  ", fail_total, " FAIL"
  if (fail_total > 0) stop 1

contains

  ! ------------------------------------------------------------------ helpers

  ! Option G assertion: relative metric vs sqrt(N) gate
  subroutine assert_golden(label, got, expected, gate, pass_count, fail_count)
    character(len=*), intent(in)    :: label
    complex(dp),      intent(in)    :: got, expected
    real(dp),         intent(in)    :: gate
    integer,          intent(inout) :: pass_count, fail_count

    real(dp) :: metric
    metric = abs(got - expected) / max(abs(expected), 1.0_dp)
    if (metric <= gate) then
      pass_count = pass_count + 1
    else
      fail_count = fail_count + 1
      write(*, '(2x,a,a,2(a,es10.3))') &
        "FAIL  ", trim(label), "  metric=", metric, "  gate=", gate
    end if
  end subroutine assert_golden

  ! Integer to string
  function itoa(n) result(s)
    integer,          intent(in) :: n
    character(len=16)            :: s
    write(s, '(i0)') n
  end function itoa

  ! ------------------------------------------------------------------ core

  subroutine run_golden_file(nlen, pass_total, fail_total)
    integer, intent(in)    :: nlen
    integer, intent(inout) :: pass_total, fail_total

    integer       :: unit_num, ios, num_cases, dummy_n, ic, k
    character(len=64)  :: case_name
    character(len=128) :: dat_path
    complex(dp), allocatable :: x_in(:), x_out_oracle(:), X_tmp(:)
    real(dp) :: re_val, im_val, gate
    integer  :: pass_case, fail_case

    ! .dat files live in build/golden/ (gitignored; generated by golden-data target)
    write(dat_path, '("build/golden/dft_n_",i0,".dat")') nlen

    open(newunit=unit_num, file=trim(dat_path), status='old', action='read', &
         form='formatted', iostat=ios)
    if (ios /= 0) then
      write(*, '(3a)') "FATAL: cannot open [", trim(dat_path), "]"
      write(*, '(a)')  "       Run: make golden-data   (or python ../../tools/json_to_fortran_data.py)"
      stop 2
    end if

    ! Header: N  num_cases  (dummy_n matches nlen; read for format compliance)
    read(unit_num, *) dummy_n, num_cases

    ! Option G gate: 1e-13 * sqrt(N)
    gate = 1.0e-13_dp * sqrt(real(nlen, dp))

    allocate(x_in(nlen), x_out_oracle(nlen))

    do ic = 1, num_cases

      ! Case name: 64-char fixed field, space-padded
      read(unit_num, '(a64)') case_name

      ! Input: N complex pairs
      do k = 1, nlen
        read(unit_num, *) re_val, im_val
        x_in(k) = cmplx(re_val, im_val, kind=dp)
      end do

      ! Oracle output: N complex pairs
      do k = 1, nlen
        read(unit_num, *) re_val, im_val
        x_out_oracle(k) = cmplx(re_val, im_val, kind=dp)
      end do

      ! dft() returns allocatable with 0-based bounds; assignment to
      ! unallocated X_tmp resets lower bound to 1 (Fortran 2018 s10.2.1.3).
      ! X_tmp(k) corresponds to X_out[k-1] (0-indexed DFT bin k-1).
      X_tmp = dft(x_in)

      pass_case = 0
      fail_case = 0
      do k = 1, nlen
        call assert_golden( &
          "N=" // trim(itoa(nlen)) // " " // trim(case_name) // " k=" // trim(itoa(k-1)), &
          X_tmp(k), x_out_oracle(k), gate, pass_case, fail_case)
      end do

      pass_total = pass_total + pass_case
      fail_total = fail_total + fail_case

      if (fail_case == 0) then
        write(*, '(2x,a,i0,2x,a,2x,i0,a,a,es9.2,a)') &
          "N=", nlen, trim(case_name), pass_case, " PASS", &
          "  gate=", gate, ""
      end if

      deallocate(X_tmp)

    end do

    deallocate(x_in, x_out_oracle)
    close(unit_num)

  end subroutine run_golden_file

end program test_dft_golden
